name: flare
services:
  flare:
    image: soulteary/flare:0.5.1
    networks:
      - traefik
    labels:
      # 用于 Traefik 服务发现
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # HTTP 相关
      # 使用 HTTP 协议访问 Flare，将使用 `http`（80端口） 提供服务
      - "traefik.http.routers.flare-http.entrypoints=http"
      # 并自动跳转至 HTTPS 协议（443端口）
      - "traefik.http.routers.flare-http.middlewares=redir-https"
      # 默认服务域名为 flare.example.com
      - "traefik.http.routers.flare-http.rule=Host(`flare.example.com`)"
      # 服务名称为 noop@internal，表示不提供任何服务 (因为自动跳转，没必要请求服务)
      - "traefik.http.routers.flare-http.service=noop@internal"
      # HTTPS 相关
      # 使用 HTTPS 协议访问 Flare，将使用 `https`（443端口） 提供服务
      - "traefik.http.routers.flare-https.entrypoints=https"
      # 在这个端口上使用 TLS 协议
      - "traefik.http.routers.flare-https.tls=true"
      # 对响应内容启用 GZIP 压缩
      - "traefik.http.routers.flare-https.middlewares=gzip"
      # 默认服务域名为 flare.example.com
      - "traefik.http.routers.flare-https.rule=Host(`flare.example.com`)"
      # （可选）HTTPS 服务名称为 flare-backend，使用 5005 端口提供服务
      # - "traefik.http.routers.flare-https.service=flare-backend"
      # 服务相关
      # 声明服务名称为 flare-backend，使用 5005 端口提供服务
      - "traefik.http.services.flare-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.flare-backend.loadbalancer.server.port=5005"

networks:
  traefik:
    external: true
