[tls.stores.default.defaultCertificate]
certFile = "/data/ssl/lab.com.crt"
keyFile = "/data/ssl/lab.com.key"

[[tls.certificates]]
certFile = "/data/ssl/lab.com.crt"
keyFile = "/data/ssl/lab.com.key"

# others...
# [[tls.certificates]]
# certFile = "/data/ssl/lab.com.crt"
# keyFile = "/data/ssl/lab.com.key"
